version: 2
jobs:
  deploy:
    environment:
      - BASH_ENV: ~/.bashrc
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      -  run:
            command: sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
      - run:
            command: curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
      - run:
            command: sudo pip install pyYAML==3.12 awsebcli --upgrade --ignore-installed
      - run:
          name: Build JSon File
          command: cd tools/scripts && ./compileJSON.py
      - run:
          name: Exit Folder
          command: cd ../../
#      - run:
#             name: install git
#             command: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install --no-install-recommends -y git
      - run:
          name: git commit
          command: |
                   if [ -n "$(git status --porcelain)" ]; then
                          echo "*** Files have been updated. ***";
                          git config --global user.name "jagadeeshwaran"
                          git config --global user.email "jagadeeshwaran.govindaraj@augustasoftsol.com"
                          git add *;
                          git commit -m "latest voter info updates1";
                          git push origin master;
                          echo "*** Files committed to git. ***";
                    else
                          echo "*** Files have not changed. Nothing to commit and upload. ***";
                    fi
      - run:
            name: upload S3
            command: aws s3 cp json s3://votersedge-voting-info-static/json --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --recursive --include "*.*";
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
